### ISSUE TITLE
Setting page font

### ISSUE THREAD

**Issue by rimmesbe** [mohaldev/prj-rev-bwfs-dasmoto#2]
Instead of having to set the font-family in all the individual  selectors you can set the pages default font with inheritance:
html { font-family: Helvetica; }
Now all elements will inherit this as their default font.

https://github.com/mohaldev/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/Resources/styles.css#L2

**Comment by mohaldev** [comment]
Yup! Would save time too.
