### ISSUE TITLE
span needs class

### ISSUE THREAD

**Issue by rimmesbe** [mohaldev/prj-rev-bwfs-dasmoto#4]
Instead of changing the styling of a span you should use a class instead. A class will add some semantic value by describing the component being styled and preserve the default styling of the span tag. 
.price { color: blue; }
This name makes it very clear what the component being styled is.

https://github.com/mohaldev/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/Resources/styles.css#L30

**Comment by mohaldev** [comment]
Got it! Thanks
