### ISSUE TITLE
strong tags

### ISSUE THREAD

**Issue by rimmesbe** [mohaldev/prj-rev-bwfs-dasmoto#5]
Besides span tags for wrapping inline text there are a few more that come with some different default styling. One is the `<strong>` tag which defaults to bold and adds some semantic weight to the text.

https://github.com/mohaldev/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L14

**Comment by irenXerex** [comment]
Another good span tag is the `<em>` tag used for emphasis.

**Comment by mohaldev** [comment]
Got it! Thanks
