### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [mohaldev/prj-rev-bwfs-dasmoto#6]
Grade: Satisfactory

Summary: Nice job on this project, the site looks good. Your HTML is very good and your code is well organized. Take a look at the issues I created for some best practices in the CSS and some new techniques that will make your life easier. If you want to learn more about component based reusable classes in CSS check out the BEM naming convention: http://getbem.com/introduction/

**Comment by mohaldev** [comment]
Thanks for the feedback and the link for further reading.
